### ISSUE TITLE
CreditCardForm -> Custom labels ( localization )

### ISSUE THREAD

**Issue by muhammedsafiulazam** [SimformSolutionsPvtLtd/flutter_credit_card#28]
We should be able to provide custom labels for "Card Number", "Expired Date", "CVV", "Card Holder". If we can do it, we can handle localization by ourselves. Thanks.

**Comment by jlaskowska** [comment]
@muhammedsafiulazam If you would like to test my solution while it is being reviewed, you can check out my branch

```yml
flutter_credit_card:
    git:
        url: https://github.com/jlaskowska/flutter_credit_card
        ref: feature/localized-text-field-hints
```

Documentation can be found [here](https://github.com/jlaskowska/flutter_credit_card/blob/feature/localized-text-field-hints/README.md#localization).
